src/main/java/org/fedoraproject/javapackages/validator/config/SymlinkConfig.java
This class is no longer used in CI.
=> Remove SymlinkConfig.RpmSetImpl class

src/main/java/org/fedoraproject/javapackages/validator/Logger.java
Make use of newer Java features:
- switch on steroids
=> Make use of newer Java features

pom.xml, src/main/java/org/fedoraproject/javapackages/validator/Check.java, src/main/java/org/fedoraproject/javapackages/validator/CheckResult.java, src/main/java/org/fedoraproject/javapackages/validator/Decorated.java, src/main/java/org/fedoraproject/javapackages/validator/ElementwiseCheck.java, src/main/java/org/fedoraproject/javapackages/validator/Logger.java, src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/RpmAttributeCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/BytecodeVersionCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/DuplicateFileCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/FilesCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/JavaExclusiveArchCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/JavadocNoarchCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/RpmFilesizeCheck.java, src/main/java/org/fedoraproject/javapackages/validator/checks/SymlinkCheck.java, src/test/java/org/fedoraproject/javapackages/validator/TestCommon.java, src/test/java/org/fedoraproject/javapackages/validator/checks/DuplicateFileCheckTest.java, src/test/java/org/fedoraproject/javapackages/validator/checks/JavaExclusiveArchCheckTest.java, src/test/java/org/fedoraproject/javapackages/validator/checks/JavadocNoarchCheckTest.java, src/test/java/org/fedoraproject/javapackages/validator/checks/RpmFilesizeCheckTest.java, src/test/java/org/fedoraproject/javapackages/validator/checks/SymlinkCheckTest.java
=> Refactorings

src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/main/resources/tmt_html/style.css
Generated HTML files can be large and slow to load in a web browser.
This PR attempts to make them smaller and load faster by not requiring web browser to invoke a CSS parser on every HTML element.
=> Optimize generated HTML

src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java, src/test/java/org/fedoraproject/javapackages/validator/TestFactory.java, src/test/resources/META-INF/services/org.fedoraproject.javapackages.validator.spi.ValidatorFactory
Adds reproducers for #82 and #84
=> Add reproducer test for various issues

src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
Add tests that check whether:
- JPV can compile source code
- validators with tmt name "/" work
=> Add more tests

src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
=> Add test case for HTML escaping

src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/main/java/org/fedoraproject/javapackages/validator/TextDecorator.java, src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
=> Fix HTML escaping

src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
=> Fix custom validator config from a yaml file not being applied

README.adoc, pom.xml, src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
Read properties file from source path and configure compiler release accordingly.
Also use Maven Resolver to add **arbitrary remote dependencies** to class path -- download them from Maven Central.
=> Alllow configuring compiler with properties file

ci_test.sh
Several small CI improvements, aimed for making it easier to run CI locally.
=> Improve CI script

src/main/java/org/fedoraproject/javapackages/validator/AnsiDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/ArgFileIterator.java, src/main/java/org/fedoraproject/javapackages/validator/Logger.java, src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/main/java/org/fedoraproject/javapackages/validator/TextDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/util/BytecodeVersionJarValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/Common.java, src/main/java/org/fedoraproject/javapackages/validator/util/DuplicateFileValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/FilesValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/RpmJarConsumer.java, src/main/java/org/fedoraproject/javapackages/validator/validators/BytecodeVersionValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/MavenMetadataValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/NVRJarMetadataValidator.java, src/test/java/org/fedoraproject/javapackages/validator/ArgFileIteratorTest.java, src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java, src/test/java/org/fedoraproject/javapackages/validator/TestCommon.java, src/test/java/org/fedoraproject/javapackages/validator/validators/DuplicateFileValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/JavaExclusiveArchValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/JavadocNoarchValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/JpmsProvidesValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/MavenMetadataValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/NVRJarMetadataValidatorTest.java, src/test/java/org/fedoraproject/javapackages/validator/validators/RpmFilesizeValidatorTest.java
Make use of more modern Java standard APIs.
Also try to make use of some of the best Java practices.
=> Use newer Java APIs and use some of best Java practices

ci_test.sh
Related: https://github.com/teemtee/tmt/issues/3027
=> Port to tmt 1.38

src/main/java/org/fedoraproject/javapackages/validator/util/Common.java, src/main/java/org/fedoraproject/javapackages/validator/util/RpmJarConsumer.java, src/main/java/org/fedoraproject/javapackages/validator/validators/JpmsProvidesValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/MavenMetadataValidator.java
Resolves https://issues.redhat.com/browse/RHEL-67337
=> JpmsProvidesValidator: Read the whole class into memory

src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
This improves MainTmtTest.testParallel() performance.
=> Make use of CountDownLatch to test parallelism

src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/main/java/org/fedoraproject/javapackages/validator/util/DuplicateFileValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/ElementwiseValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/NVRJarMetadataValidator.java, src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java
See https://openjdk.org/jeps/456
=> Use unnamed variables (JEP 456)

src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java, src/main/java/org/fedoraproject/javapackages/validator/NamedResult.java
=> Switch to ISO_OFFSET_DATE_TIME format for results.yaml

src/main/java/org/fedoraproject/javapackages/validator/AnsiDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/ArgFileIterator.java, src/main/java/org/fedoraproject/javapackages/validator/DefaultValidator.java, src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/Logger.java, src/main/java/org/fedoraproject/javapackages/validator/NamedResult.java, src/main/java/org/fedoraproject/javapackages/validator/TextDecorator.java
=> Improve Javadocs

README.adoc, pom.xml, src/main/java/org/fedoraproject/javapackages/validator/AnsiDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/ArgFileIterator.java, src/main/java/org/fedoraproject/javapackages/validator/DefaultValidator.java, src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/Logger.java, src/main/java/org/fedoraproject/javapackages/validator/Main.java, src/main/java/org/fedoraproject/javapackages/validator/NamedResult.java, src/main/java/org/fedoraproject/javapackages/validator/TextDecorator.java, src/main/java/org/fedoraproject/javapackages/validator/util/BytecodeVersionJarValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/Common.java, src/main/java/org/fedoraproject/javapackages/validator/util/DuplicateFileValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/ElementwiseValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/FilesValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/JarValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/RpmAttributeValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/RpmFilesizeValidator.java, src/main/java/org/fedoraproject/javapackages/validator/util/RpmJarConsumer.java, src/main/java/org/fedoraproject/javapackages/validator/validators/BytecodeVersionValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/JavaExclusiveArchValidator.java, src/main/java/org/fedoraproject/javapackages/validator/validators/MavenMetadataValidator.java
See: https://openjdk.org/jeps/467
=> Switch to Markdown javadoc comments

Dockerfile.main
=> Run with Java 24

src/main/java/org/fedoraproject/javapackages/validator/validators/JavaExclusiveArchValidator.java
=> Make java_arches of JavaExclusiveArchValidator configurable
