Dockerfile.ci

Fedora cloud images have tsflags=nodocs setting in dnf.conf, which
cause envroot packages not to install docs.

[ci] Set empty tsflags while populating envroot

---

prepare_ci.sh

Fedora CI tests only x86_64 RPMs.

[ci] Limit archful RPMs to x86_64

---

src/main/java/org/fedoraproject/javapackages/validator/Check.java

`Main.getTestRpms()` is never null.

Throw an exception when no rpms are found

---

Dockerfile.main
pom.xml
run.sh

This change makes the container from 400 to 218 MB. Alpine is supported for 2 years.

Minimize executable container image

---

src/main/java/org/fedoraproject/javapackages/validator/ArgFileIterator.java
src/main/java/org/fedoraproject/javapackages/validator/Check.java
src/main/java/org/fedoraproject/javapackages/validator/ElementwiseCheck.java
src/main/java/org/fedoraproject/javapackages/validator/Main.java
src/main/java/org/fedoraproject/javapackages/validator/RpmAttributeCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/BytecodeVersionCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/DuplicateFileCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/FilesCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/JavaExclusiveArchCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/JavadocNoarchCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/RpmFilesizeCheck.java
src/main/java/org/fedoraproject/javapackages/validator/checks/SymlinkCheck.java
src/test/java/org/fedoraproject/javapackages/validator/TestCommon.java
src/test/java/org/fedoraproject/javapackages/validator/checks/DuplicateFileCheckTest.java
src/test/java/org/fedoraproject/javapackages/validator/checks/JavaExclusiveArchCheckTest.java
src/test/java/org/fedoraproject/javapackages/validator/checks/JavadocNoarchCheckTest.java
src/test/java/org/fedoraproject/javapackages/validator/checks/SymlinkCheckTest.java

Removed `Main.getTestRpms`, because the only consumer stopped needing them. I don't want to keep them accessible unless there is a reason to.

Refactorings + removing `getTestRpms`

---

src/main/java/org/fedoraproject/javapackages/validator/Main.java

The dependency/ directory may be absent.  In this case don't try to list files in it.

Avoid expanding dependency/ directory when it doesn't exist

---

src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java

When testing MainTmt it is useful to programatically create it from Java code and pass values of TMT_TEST_DATA and TMT_TREE directly, without using system environment.

Allow creating MainTmt without env variables

---

src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java
src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java

When JPV itself crashes with an exception it should still write results.yaml with error result containing exception stack trace.

Upon crash write results.yaml with crash.log

---

src/main/java/org/fedoraproject/javapackages/validator/validators/MavenMetadataValidator.java

Packages without Maven metadata are perfectly fine, so we should not bother users to check them by using "info" result. Instead, use the "skip" result.
Also check for JARs and POMs without Maven metadata.
To be backwards-compatible with older Fedora branches, for now don't fail when there are JARs and POMs without metadata, but "info" instead.
Fixes #88

Improve Maven metadata validation

---

Dockerfile.main
src/main/java/org/fedoraproject/javapackages/validator/util/Common.java

Also add javadoc step to CI to ensure javadocs remain buildable.
Fixes #91

Make javadocs buildable

---

src/main/java/org/fedoraproject/javapackages/validator/Main.java
src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java

Resolves: #94
The output of the test looks like this:
```
java.lang.RuntimeException: Failed to compile sources:
/tmp/junit452872596119397772/Boom.java:1: error: package java.util.foo does not exist
package pkg; import java.util.foo.bar; class Boom{}
^
1 error
at org.fedoraproject.javapackages.validator.Main.compileFiles(Main.java:187)
at org.fedoraproject.javapackages.validator.Main.discover(Main.java:349)
at org.fedoraproject.javapackages.validator.Main.run(Main.java:597)
at org.fedoraproject.javapackages.validator.MainTmt.run(MainTmt.java:314)
at org.fedoraproject.javapackages.validator.MainTmtTest.runMain(MainTmtTest.java:67)
at org.fedoraproject.javapackages.validator.MainTmtTest.testCompilationFailure(MainTmtTest.java:173)
at …
```

Add the compiler output to the message of the thrown exception when the runtime compilation of Validator sources fails

---

src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java
src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java
src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java

The HTML decorator would only escape the inner contents of the Decorated class, not the whole text which is still inside a `<text>` block.
Resolves: #82

Fix line breaks missing from the HTML output

---

Dockerfile.ci
Makefile
ci_test.sh
prepare_ci.sh

Run validator once on all packages.
This improves CI performance **a lot** (like from 11m 48s down to 1m 36s).
We can do that now as we don't have anything specific in component test plans any longer.
And we won't have as our nightly test runs (project Gacek) execute JPV tests in the same way -- all packages at once.
Also use two-stage build for CI image -- the resulting image is Alpine-based, which makes it a bit smaller.
Also update CI component list.

In CI run validator just once

---

Dockerfile.main
README.adoc
pom.xml
run.sh
src/main/java/org/fedoraproject/javapackages/validator/Main.java
src/test/java/org/fedoraproject/javapackages/validator/validators/DuplicateFileValidatorTest.java

Switch to Java 22:
- Use non-preview [FFM API](https://openjdk.org/jeps/454)
Switch to java-deptools-native 1.2.0:
- This release contains significant performance improvements.
- It supports files without content (#86).
Closes #104

Switch to Java 22

---

src/main/java/org/fedoraproject/javapackages/validator/Main.java

Several improvements to logging for dependency resolution.
JPV logs now include entries like:
```
[DEBUG] Using remote repository central at https://repo.maven.apache.org/maven2
[DEBUG] Using remote repository repo0 at https://s01.oss.sonatype.org/content/repositories/snapshots
[DEBUG] Resolved dependency io.kojan:runit-api:jar:1.0.0-20240731.120908-1 from repository repo0
[DEBUG] Resolved dependency io.kojan:runit-validator:jar:1.0.0-20240731.120908-1 from repository repo0
[DEBUG] Resolved dependency org.apiguardian:apiguardian-api:jar:1.1.2 from repository central
[DEBUG] Resolved dependency org.hamcrest:hamcrest:jar:2.2 from repository central
[DEBUG] Resolved dependency org.junit.jupiter:junit-jupiter-api:jar:5.10.0 from repository central
[DEBUG] Resolved dependency …
```

Logging improvements

---

src/main/java/org/fedoraproject/javapackages/validator/validators/NVRJarMetadataValidator.java
src/test/java/org/fedoraproject/javapackages/validator/validators/NVRJarMetadataValidatorTest.java

Such files may be examples, demos and other resources that do not need to follow the packaging guidelines,

NVRJarMetadataValidator: skip Jar files installed in nonstandard locations (`/usr/share/java`, `/usr/lib/java`)

---

src/test/java/org/fedoraproject/javapackages/validator/MainTmtTest.java

The point is that MainTmtTest should test MainTmt in isolation and not rely on any validators in default factory.

Always use TestFactory during tests

---

Dockerfile.ci

Need to incorporate fix from https://bodhi.fedoraproject.org/updates/FEDORA-2024-fbc8bc3e71
Related: https://issues.redhat.com/browse/RHEL-53194

Rebuild CI image

---

Dockerfile.main
pom.xml
run.sh
src/main/java/org/fedoraproject/javapackages/validator/Main.java

Build super JAR with maven-assembly-plugin instead of thin JAR and `dependencies/` directory created wit help of maven-dependency-plugin
Fat JAR is built as `target/validator.jar`. It contains validator and all dependencies. Suitable for running with `java -jar`. Suitable for running from `tmt`.
Thin JAR without class-path is built as `target/validator-2.0.0-SNAPSHOT.jar`. Suitable for using as dependency once it will be deployed to Maven Central. Not suitable for `java -jar`.

Build super JAR with maven-assembly-plugin

---

src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java
src/main/resources/tmt_html/style.css
src/test/java/org/fedoraproject/javapackages/validator/HtmlTablePrintStreamTest.java

Currently it's hard to read Validator HTML reports due to poor selection of colors and in some cases low contrast (eg. yellow text on white background).
Instead of inventing a new color scheme, I propose to use [Solarized](https://ethanschoonover.com/solarized): a set of carefully selected colors designed for use in applications like Validator. Solarized improves readability and reduces eye fatigue.
I understand that this is a subjective matter (_de gustibus non est disputandum_), so feel free to ignore/close this PR.

Switch to Solarized color palette

---

Dockerfile.main
run.sh

Java 22 is still the minimal target, but Dockerfiles will use Java 23.

Build and run with Java 23

---

pom.xml
run.sh
src/main/resources-filtered/JAVA_HOME

For run.sh script use the same Java as for running unit tests, but let the user override by setting JAVA_HOME explicitly.
Related: #166

run.sh: Use JAVA_HOME from Maven build

---

Dockerfile.main

An attempt to minimize the JVM size to only the needed parts.
My size listing shows:
```
$ podman images javapackages-validator --format "{{.Repository}}:{{.Tag}} -> {{.Size}}"
quay.io/fedora-java/javapackages-validator:latest -> 550 MB
$ podman images jpv --format "{{.Repository}}:{{.Tag}} -> {{.Size}}"
localhost/jpv:latest -> 199 MB
```
Assuming JPV works correctly, this looks like a very good improvement.

Use jlink to minimize runtime container size

---

src/main/java/org/fedoraproject/javapackages/validator/Main.java

Class `SessionBuilderSupplier` (from Maven Resolver)
extends `MavenSessionBuilderSupplier` (from Maven), which
implements `Supplier<SessionBuilder>` (from Java base).
Method `get()` was deprecated in `MavenSessionBuilderSupplier`,
and deprecation is inherited by `SessionBuilderSupplier`, although it shouldn't be.
To work this around we cast the instance of `SessionBuilderSupplier` to `Supplier<SessionBuilder>`
and invoke its `get()` method, which is not deprecated.

Silence deprecation warning in Maven Resolver

---

src/main/java/org/fedoraproject/javapackages/validator/MainTmt.java

Embed resources  `filter.js` and `style.css` directly in generated HTML files to make them self-contained to ease sharing.
The external resources make it hard to share generated HTML with others.
In contrast, with standalone HTML it's super-easy to attach the HTML file and upload it somewhere, or send it over email, instant messaging etc.
The resource files are small-enough to justify embedding them.
JQuery remains an external resource, but it is available from anywhere, so it doesn't need to be embedded.

Make generated HTML self-contained

---

Dockerfile.main

I believe this is the cause of failing quay.io builds.

Remove asterisk from Dockerfile

---

src/main/java/org/fedoraproject/javapackages/validator/Main.java

When compiling sources, the following note is printed:
```
Note: Annotation processing is enabled because one or more processors were found
on the class path. A future release of javac may disable annotation processing
unless at least one processor is specified by name (-processor), or a search
path is specified (--processor-path, --processor-module-path), or annotation
processing is enabled explicitly (-proc:only, -proc:full).
Use -Xlint:-options to suppress this message.
Use -proc:none to disable annotation processing.
```

Disable annotation processing when compiling sources

---

src/main/java/org/fedoraproject/javapackages/validator/validators/NoJavadocValidator.java

Add validator which checks for the absence of -javadoc subpackages

---

Dockerfile.main

RHEL 9.6 is GA, time to start using `maven-unbound`.

Build with Maven 3.9 unbound from RHEL 9.6+
